<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- This is a parametric description of reseq mK1 arm -->

  <joint name="arm_mK1_joint" type="revolute">
    <parent link="chassis1_link"/>
    <child link="arm_mK1_link"/>
    <!-- Effort in Nm, angle in radians -->
    <limit effort="10.0" lower="-${pi*0.001}" upper="${pi/2}" velocity="0.5"/>
    <origin xyz="${WheelBase/2} 0 0" rpy="${pi/2} 0 0" />
    <axis xyz="0 0 1"/>
  </joint>

  <link name="arm_mK1_link">
    <!-- cylinder to the right -->
    <visual>
      <origin xyz="0 0 ${ForkThickness/2+toll+ModuleWidth/2}" />
      <geometry>
        <cylinder radius="${ForkHeight/2}" length="${ForkThickness}"/>
      </geometry>
      <material name="ArmColor"/>
    </visual>
    <!-- cylinder to the left -->
    <visual>
      <origin xyz="0 0 -${ForkThickness/2+toll+ModuleWidth/2}" />
      <geometry>
        <cylinder radius="${ForkHeight/2}" length="${ForkThickness}"/>
      </geometry>
      <material name="ArmColor"/>
    </visual>
    <!-- right side of the fork -->
    <visual>
      <origin xyz="${(toll+EquivalentWheelDiameter/2)/2} 0 ${ForkThickness/2+toll+ModuleWidth/2}" />
      <geometry>
        <box size="${toll+EquivalentWheelDiameter/2} ${ForkHeight} ${ForkThickness}"/>
      </geometry>
      <material name="ArmColor"/>
    </visual>
    <!-- left side of the fork -->
    <visual>
      <origin xyz="${(toll+EquivalentWheelDiameter/2)/2} 0 -${ForkThickness/2+toll+ModuleWidth/2}" />
      <geometry>
        <box size="${toll+EquivalentWheelDiameter/2} ${ForkHeight} ${ForkThickness}"/>
      </geometry>
      <material name="ArmColor"/>
    </visual>
    <!-- front side of the fork -->
    <visual>
      <origin xyz="${ForkThickness/2+toll+EquivalentWheelDiameter/2} 0 0" />
      <geometry>
        <box size="${ForkThickness} ${ForkHeight} ${ModuleWidth+(toll+ForkThickness)*2}"/>
      </geometry>
      <material name="ArmColor"/>
    </visual>
    <!-- Jetson holder -->
    <visual>
      <origin xyz="${ForkThickness/2+toll+EquivalentWheelDiameter/2+JetsonHolderLength/2} 0 0" />
      <geometry>
        <box size="${JetsonHolderLength} ${ForkHeight} ${JetsonHolderWidth}"/>
      </geometry>
      <material name="ArmColor"/>
    </visual>

    <!-- cylinder to the right -->
    <collision>
      <origin xyz="0 0 ${ForkThickness/2+toll+ModuleWidth/2}" />
      <geometry>
        <cylinder radius="${ForkHeight/2}" length="${ForkThickness}"/>
      </geometry>
    </collision>
    <!-- cylinder to the left -->
    <collision>
      <origin xyz="0 0 -${ForkThickness/2+toll+ModuleWidth/2}" />
      <geometry>
        <cylinder radius="${ForkHeight/2}" length="${ForkThickness}"/>
      </geometry>
    </collision>
    <!-- front side of the fork -->
    <collision>
      <origin xyz="${ForkThickness/2+toll+EquivalentWheelDiameter/2} 0 0" />
      <geometry>
        <box size="${ForkThickness} ${ForkHeight} ${ModuleWidth+(toll+ForkThickness)*2}"/>
      </geometry>
    </collision>
    <!-- Jetson holder -->
    <collision>
      <origin xyz="${ForkThickness/2+toll+EquivalentWheelDiameter/2+JetsonHolderLength/2} 0 0" />
      <geometry>
        <box size="${JetsonHolderLength} ${ForkHeight} ${JetsonHolderWidth}"/>
      </geometry>
    </collision>

    <xacro:inertial_box mass="${0.5}" x="${ForkHeight}" y="${JetsonHolderLength}" z="${JetsonHolderWidth}">
      <origin xyz="${ForkThickness/2+toll+EquivalentWheelDiameter/2+JetsonHolderLength/2} 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <gazebo reference="arm_mK1_link">
    <material>Gazebo/Grey</material>
  </gazebo>

</robot>