# CAN bus package identifiers

BATTERY_CHARGE = 0x11
BATTERY_VOLTAGE = 0x12
BATTERY_TEMP = 0x13

MOTOR_SETPOINT = 0x21
MOTOR_FEEDBACK = 0x22
MOTOR_TEMP = 0x23
MOTOR_CURRENT = 0x24

JOINT_YAW_SETPOINT = 0x31
JOINT_YAW_FEEDBACK = 0x32
JOINT_PITCH_SETPOINT = 0x33
JOINT_PITCH_FEEDBACK = 0x34
JOINT_ROLL_SETPOINT = 0x35
JOINT_ROLL_FEEDBACK = 0x36

#TODO: consider using two dictionaries topic_hex->topic and topic_name->hex instead
