services:
  reseq:
    build:
      dockerfile: docker/Dockerfile.orin
    image: reseq:orin
    privileged: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    stdin_open: true
    tty: true
    restart: "no"
    volumes:
      - ../output:/output
      - /home/isaac/maps:/ros2_ws/maps
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
    entrypoint: /bin/bash
