<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- 
    Creates the joint between two consecutive chassis. It assumes that two 
    consecutive chassis have a consecutive id. This macro must be called between
    the definition of the two chassis

    @param id: the id of the joint (which is assumed part of the chassis behind)
   -->
  <xacro:macro name="chassis_joint_factory" params="id">
    <!-- JointR -->
    <joint name="mod${id}__roll_joint" type="revolute">
      <parent link="chassis${id-1}_link" />
      <child link="joint_r_${id}_link" />
      <!-- Effort in Nm -->
      <limit effort="2.0" lower="${-roll}" upper="${roll}" velocity="0.5" />
      <origin xyz="-${WheelBase/2} 0 0" rpy="0 0 0" />
      <axis xyz="1 0 0" />
    </joint>

    <link name="joint_r_${id}_link">
      <xacro:replicate_collision>
        <visual>
          <origin xyz="-${JointB/2} 0 0" rpy="0 ${pi/2} 0" />
          <geometry>
            <cylinder radius="${JointWidth/2}" length="${JointB}" />
          </geometry>
          <material name="JointColor" />
        </visual>
      </xacro:replicate_collision>

      <xacro:inertial_cylinder_x mass = "${JointBMass}"
        length = "${JointB}"
        radius = "${JointWidth/2}">
        <origin xyz="-${JointB/2} 0 0" rpy="0 ${pi/2} 0" />
      </xacro:inertial_cylinder_x>  

    </link>

    <gazebo reference="joint_r_${id}_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- JointY -->
    <joint name="mod${id}__yaw_joint" type="revolute">
      <parent link="joint_r_${id}_link" />
      <child link="joint_y_${id}_link" />
      <!-- Effort in Nm -->
      <limit effort="20.0" lower="${-yaw}" upper="${yaw}" velocity="0.5" />
      <origin xyz="-${JointB} 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="joint_y_${id}_link">
      <!-- to hide space wile rotating -->
      <xacro:replicate_collision>
        <visual>
          <geometry>
            <sphere radius="${JointWidth/2}" />
          </geometry>
          <material name="JointColor" />
        </visual>
      </xacro:replicate_collision>

      <!-- horizontal shaft -->
      <xacro:replicate_collision>
        <visual>
          <origin xyz="-${JointA/2} 0 0" rpy="${pi/2} 0 0" />
          <geometry>
            <box
              size="${JointA} ${EquivalentWheelDiameter-2*JointABottomClearance} ${JointWidth}" />
          </geometry>
          <material name="JointColor" />
        </visual>
      </xacro:replicate_collision>

      <xacro:inertial_box mass="${JointAMass}" x="${JointA}" y="${EquivalentWheelDiameter-2*JointABottomClearance}" z="${JointWidth}">
        <origin xyz="-${JointA/2} 0 0" rpy="0 0 0" />
      </xacro:inertial_box>

    </link>

    <gazebo reference="joint_y_${id}_link">
      <material>Gazebo/Grey</material>
    </gazebo>


    <!-- JointP -->
    <joint name="mod${id}__pitch_joint" type="revolute">
      <parent link="joint_y_${id}_link" />
      <child link="joint_p_${id}_link" />
      <!-- Effort in Nm -->
      <limit effort="20.0" lower="${-pitch}" upper="${pitch}" velocity="0.5" />
      <origin xyz="${-JointA} 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </joint>

    <link name="joint_p_${id}_link">
      <!-- gearbox cilinder -->
      <xacro:replicate_collision>
        <visual>
          <origin rpy="${pi/2} 0 0" />
          <geometry>
            <cylinder radius="${JointDiameter/2}" length="${ModuleWidth-2*TrackWidth-toll*2}" />
          </geometry>
          <material name="JointColor" />
        </visual>
      </xacro:replicate_collision>
    </link>

    <gazebo reference="joint_p_${id}_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="chassis${id}_joint" type="fixed">
      <parent link="joint_p_${id}_link" />
      <child link="chassis${id}_link" />
      <origin xyz="${-WheelBase/2} 0 0" rpy="0 0 0" />
    </joint>

  </xacro:macro>

</robot>