agevar_consts:
  a: 0.215                  # [m] Distance between the center of every module and the previous yaw joint
  b: 0.1946                 # [m] Distance between the center of every module and the following yaw joint
  d: 0.1281                 # [m] Distance between pair of equivalent wheels
  r_eq: 0.0609              # [m] Radius of the equivalent wheels