agevar_consts:
  a: 0.1850                 # [m] Distance between the center of every module and the previous yaw joint
  b: 0.2345                 # [m] Distance between the center of every module and the following yaw joint
  d: 0.1536                 # [m] Distance between pair of equivalent wheels (narrow tracks)
  r_eq: 0.0609              # [m] Radius of the equivalent wheels