---
canbus:
  channel: "vcan0"
modules:
  - address: 0x21
    hasJoint: true
    hasEndEffector: false
  - address: 0x22
    hasJoint: true
    hasEndEffector: false
  - address: 0x23
    hasJoint: true
    hasEndEffector: false
  - address: 0x24
    hasJoint: true
    hasEndEffector: false
dimensions:
  a: 0.205       # [m] Distance between the center of every module and the previous yaw joint
  b: 0.185       # [m] Distance between the center of every module and the following yaw joint
  d: 0.12        # [m] Distance between pair of equivalent wheels
  r_eq: 0.06     # [m] Radius of the equivalent wheels
