xacro:
  WheelBase: 0.137
  ModuleWidth: 0.27
  TrackWidth: 0.052
  ChassisTopAndBottomClearance: 0.013
  WheelMass: 0.1
  ChassisMass: 2.5

  JointDiameter: 0.048
  JointABottomClearance: 0.013
  JointAMass: 0.1
  JointBMass: 0.05
  JointWidth: 0.067 # At the moment ${EquivalentWheelDiameter-2*JointABottomClearance}

  ForkThickness: 0.02
  ForkHeight: 0.05
  JetsonHolderWidth: 0.085
  JetsonHolderLength: 0.158
  CylinderOnJetsonLength: 0.085
  CylinderOnJetsonRadius: 0.026
  CylinderOnJetsonShift: 0.012
  CylinderRealsenseLength: 0.055
  CylinderRealsenseRadius: 0.026
  RealsenseHeight: 0.02
  RealsenseLength: 0.026
  RealsenseWidth: 0.09
  RealsenseOriginSystem: 0.0162