realsense: 
  realsense2_camera_node: 
    ros__parameters:
      enable_color: true
      enable_depth: true
      enable_infra1: false
      enable_infra2: false
      enable_gyro: false
      enable_accel: false

      rgb_camera:
        color_format: RGB8
        color_profile: 640X480X30
      align_depth:
        enable: true

      ".realsense2_camera_node.color.image_raw.jpeg_quality": 30
      ".realsense2_camera_node.depth.image_rect_raw.format": png
      ".realsense2_camera_node.depth.image_rect_raw.png_level": 9
      
      wait_for_device_timeout: 10.0 
