---
include:
  xacro: digital_twin_params_mk2.yaml
  joint_pub_consts: joint_pub_consts.yaml
  enea_consts: enea_consts.yaml
  scaler_consts: scaler_consts.yaml
  agevar_consts: agevar_consts_mk2.yaml
version: "mk2"
canbus:
  channel: "can1"
num_modules: 2
modules:
  - address: 0x21
    hasJoint: true
    hasEndEffector: false
  - address: 0x22
    hasJoint: true
    hasEndEffector: false
realsense_config: "realsense_rgb_motion.yaml"
sensors:
  - realsense: true
  - lidar: true