---
version: "mk2"
canbus:
  channel: "vcan0"
modules:
  - address: 0x11
    hasJoint: false
    hasEndEffector: true
  - address: 0x12
    hasJoint: true
    hasEndEffector: false
  - address: 0x13
    hasJoint: true
    hasEndEffector: false
geometric_consts:
  a: 0.18                    # [m] Distance between the center of every module and the previous yaw joint
  b: 0.18                    # [m] Distance between the center of every module and the following yaw joint
  d: 0.223                   # [m] Distance between pair of equivalent wheels
  r_eq: 0.0465               # [m] Radius of the equivalent wheels
