scaler_consts:
  r_linear_vel:              # [m/s] Range of the linear velocity
    - -0.27017
    - 0.27017
  r_inverse_radius:          # [1/m] Range of the inverse radius of curvature
    - -1.5385
    - 1.5385
  r_pitch_vel:               # [LSB/s] Range of pitch velocity
    - -183
    - 183
  r_head_pitch_vel:          # [LSB/s] Range of indepepndent head pitch velocity
    - -400
    - 400
  r_head_roll_vel:            # [LSB/s] Range of head roll velocity
    - -455
    - 455