scaler_consts:
  r_linear_vel:              # [m/s] Range of the linear velocity (agevar mode)
    - -0.1600
    - 0.1600
  r_inverse_radius:          # [1/m] Range of the inverse radius of curvature (agevar mode)
    - -2.5478
    - 2.5478
  r_angular_vel:             # [rad/s] Range of the angular velocity (pivot mode)
    - -2.4912
    - 2.4912
