<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- 
    Defines the current chassis

    @param id: the id of the chassis (starting from 1)
  -->
  <xacro:macro name="chassis" params="id">

    <link name="chassis${id}_link">
      <xacro:replicate_collision>
        <visual>
          <origin xyz="-${EquivalentWheelDiameter/12+(toll+JointDiameter/2)/2} 0 0" />
          <geometry>
            <!-- leaving 1/3 of the EquivalentWheelDiameter from front and toll from Joint and
            Tracks (for clearance) -->
            <box
              size="${WheelBase-JointDiameter/2-toll+EquivalentWheelDiameter*2/3-EquivalentWheelDiameter/2} ${ModuleWidth-2*TrackWidth-2*toll} ${EquivalentWheelDiameter-2*ChassisTopAndBottomClearance}" />
          </geometry>
          <material name="ChassisColor" />
        </visual>
      </xacro:replicate_collision>

      <xacro:inertial_box mass="${ChassisMass}"
        x="${WheelBase-JointDiameter/2-toll+EquivalentWheelDiameter*2/3-EquivalentWheelDiameter/2}"
        y="${ModuleWidth-2*TrackWidth-2*toll}"
        z="${EquivalentWheelDiameter-2*ChassisTopAndBottomClearance}">
        <origin xyz="${EquivalentWheelDiameter/12+(toll+JointDiameter/2)/2} 0 0" rpy="0 0 0" />
      </xacro:inertial_box>
    </link>

    <!-- LEFT FRONT WHEEL 1-->
    <joint name="left_front_wheel_${id}_joint" type="continuous">
      <parent link="chassis${id}_link" />
      <child link="left_front_wheel_${id}_link" />
      <origin xyz="${WheelBase/2} ${ModuleWidth/2-TrackWidth/2} 0" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="left_front_wheel_${id}_link">
      <visual>
        <geometry>
          <cylinder radius="${EquivalentWheelDiameter/2}" length="${TrackWidth}" />
        </geometry>
        <material name="WheelColor" />
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${EquivalentWheelDiameter/2}" length="${TrackWidth}" />
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${WheelMass}" length="${TrackWidth}"
        radius="${EquivalentWheelDiameter/2}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_cylinder>
    </link>


    <!-- RIGHT FRONT WHEEL 1-->
    <joint name="right_front_wheel_${id}_joint" type="continuous">
      <parent link="chassis${id}_link" />
      <child link="right_front_wheel_${id}_link" />
      <origin xyz="${WheelBase/2} ${-ModuleWidth/2+TrackWidth/2} 0" rpy="${pi/2} 0 0" />
      <axis xyz="0 0 -1" />
    </joint>

    <link name="right_front_wheel_${id}_link">
      <visual>
        <geometry>
          <cylinder radius="${EquivalentWheelDiameter/2}" length="${TrackWidth}" />
        </geometry>
        <material name="WheelColor" />
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${EquivalentWheelDiameter/2}" length="${TrackWidth}" />
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${WheelMass}" length="${TrackWidth}"
        radius="${EquivalentWheelDiameter/2}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_cylinder>
    </link>


    <!-- LEFT BACK WHEEL 1-->
    <joint name="left_back_wheel_${id}_joint" type="continuous">
      <parent link="chassis${id}_link" />
      <child link="left_back_wheel_${id}_link" />
      <origin xyz="${-WheelBase/2} ${ModuleWidth/2-TrackWidth/2} 0" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="left_back_wheel_${id}_link">
      <visual>
        <geometry>
          <cylinder radius="${EquivalentWheelDiameter/2}" length="${TrackWidth}" />
        </geometry>
        <material name="WheelColor" />
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${EquivalentWheelDiameter/2}" length="${TrackWidth}" />
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${WheelMass}" length="${TrackWidth}"
        radius="${EquivalentWheelDiameter/2}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_cylinder>
    </link>


    <!-- RIGHT BACK WHEEL 1-->
    <joint name="right_back_wheel_${id}_joint" type="continuous">
      <parent link="chassis${id}_link" />
      <child link="right_back_wheel_${id}_link" />
      <origin xyz="${-WheelBase/2} ${-ModuleWidth/2+TrackWidth/2} 0" rpy="${pi/2} 0 0" />
      <axis xyz="0 0 -1" />
    </joint>

    <link name="right_back_wheel_${id}_link">
      <visual>
        <geometry>
          <cylinder radius="${EquivalentWheelDiameter/2}" length="${TrackWidth}" />
        </geometry>
        <material name="WheelColor" />
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${EquivalentWheelDiameter/2}" length="${TrackWidth}" />
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${WheelMass}" length="${TrackWidth}"
        radius="${EquivalentWheelDiameter/2}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_cylinder>
    </link>

  </xacro:macro>

</robot>