<?xml version="1.0"?>
<package format="3">
  <name>2_Sloped_KRails</name>
  <version>1.0.0</version>
  <description>URDF/mesh package for the sloped RoboCup Rescue KRails arena</description>
  <maintainer email="team@teamisaac.it">Team Isaac</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
