<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- This is a parametric description of reseq mK1 arm -->

  <joint name="arm_pitch_1_joint" type="revolute">
    <parent link="chassis1_link"/>
    <child link="arm_mk1_link"/>
    <!-- Effort in Nm, angle in radians -->
    <limit effort="10.0" lower="${pi*0.01}" upper="-${pi/2}" velocity="0.5"/>
    <origin xyz="${WheelBase/2} 0 0" />
    <axis xyz="0 1 0"/>
  </joint>

  <link name="arm_mk1_link"> 
    <!-- cylinder to the right -->
    <xacro:replicate_collision>
      <visual>
        <origin xyz="0 ${-(ForkThickness/2+toll+ModuleWidth/2)} 0" rpy = "${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${ForkHeight/2}" length="${ForkThickness}"/>
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>

    <!-- cylinder to the left -->
    <xacro:replicate_collision>
      <visual>
        <origin xyz="0 ${(ForkThickness/2+toll+ModuleWidth/2)} 0" rpy = "${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${ForkHeight/2}" length="${ForkThickness}"/>
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>

    <!-- right side of the fork -->
    <xacro:replicate_collision>
      <visual>
        <origin xyz="${(toll+EquivalentWheelDiameter/2)/2} -${ForkThickness/2+toll+ModuleWidth/2} 0" rpy = "${pi/2} 0 0"/>
        <geometry>
          <box size="${toll+EquivalentWheelDiameter/2} ${ForkHeight} ${ForkThickness}"/>
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>   

    <!-- left side of the fork -->
    <xacro:replicate_collision>
      <visual>
        <origin xyz="${(toll+EquivalentWheelDiameter/2)/2} ${ForkThickness/2+toll+ModuleWidth/2} 0" rpy = "${pi/2} 0 0"/>
        <geometry>
          <box size="${toll+EquivalentWheelDiameter/2} ${ForkHeight} ${ForkThickness}"/>
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>       

    <!-- front side of the fork -->
    <xacro:replicate_collision>
      <visual>
        <origin xyz="${ForkThickness/2+toll+EquivalentWheelDiameter/2} 0 0" rpy = "${pi/2} 0 0"/>
        <geometry>
          <box size="${ForkThickness} ${ForkHeight} ${ModuleWidth+(toll+ForkThickness)*2}"/>
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>  

    <!-- Jetson holder -->
    <xacro:replicate_collision>
      <visual>
        <origin xyz="${ForkThickness/2+toll+EquivalentWheelDiameter/2+JetsonHolderLength/2} 0 0" rpy = "${pi/2} 0 0"/>
        <geometry>
          <box size="${JetsonHolderLength} ${ForkHeight} ${JetsonHolderWidth}"/>
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>

    <xacro:inertial_box mass="${0.5}" x="${JetsonHolderLength}" z="${ForkHeight}" y="${JetsonHolderWidth}">
      <origin xyz="${ForkThickness/2+toll+EquivalentWheelDiameter/2+JetsonHolderLength/2} 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>

    <!-- cylinder on the jetson holder-->
    <xacro:replicate_collision>
      <visual>
        <origin xyz ="${ForkThickness/2+toll+EquivalentWheelDiameter/2+JetsonHolderLength + CylinderOnJetsonLength/2} 0 ${CylinderOnJetsonShift}" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${CylinderOnJetsonRadius}" length="${CylinderOnJetsonLength}"/>
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>

  </link>

  <gazebo reference="arm_mk1_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- head pitch joint-->
  <joint name="arm_head_pitch_1_joint" type="revolute">
    <parent link="arm_mk1_link"/>
    <child link="arm_camera_holder_intermediate"/>
    <!-- Effort in Nm, angle in radians -->
    <limit effort="10.0" lower="0" upper="-${pi}" velocity="0.5"/>
    <origin xyz ="${ForkThickness/2+toll+EquivalentWheelDiameter/2+JetsonHolderLength + CylinderOnJetsonLength} 0 ${CylinderOnJetsonShift}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="arm_camera_holder_intermediate">

  </link>

  <gazebo reference="arm_camera_holder_intermediate">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- head roll joint -->
  <joint name="arm_head_roll_1_joint" type="revolute">
    <parent link="arm_camera_holder_intermediate"/>
    <child link="arm_camera_holder"/>
    <!-- Effort in Nm, angle in radians -->
    <limit effort="10.0" lower="${-5*(pi/6)}" upper="${5*(pi/6)}" velocity="0.5"/>
    <origin xyz ="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>


  <link name="arm_camera_holder">

    <!-- cylinder between realsense and rotation axis -->
    <xacro:replicate_collision>
      <visual>
        <origin xyz ="0 0 -${CylinderRealsenseLength/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${CylinderRealsenseRadius}" length="${CylinderRealsenseLength}"/>
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>   
  
    <!-- sphere -->
    <xacro:replicate_collision>
      <visual>
        <origin xyz ="0 0 0" rpy="${pi/2} ${pi} ${pi}"/>
        <geometry> 
          <sphere radius="${CylinderRealsenseRadius}"/> 
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>

    <!-- realsense holder -->
    <xacro:replicate_collision>
      <visual>
        <origin xyz ="0 0 -${CylinderRealsenseLength + RealsenseLength/2}" rpy="0 ${pi/2} 0"/>
        <geometry>
          <box size="${RealsenseLength} ${RealsenseWidth} ${RealsenseHeight}"/>
        </geometry>
        <material name="ArmColor"/>
      </visual>
    </xacro:replicate_collision>

    <xacro:inertial_box mass="0.5" x="${RealsenseLength}" y="${RealsenseWidth}" z="${RealsenseHeight}">
      <origin xyz ="0 0 -${CylinderRealsenseLength + RealsenseLength/2}" rpy="0 ${pi/2} 0"/>
    </xacro:inertial_box>       
    
  </link>

  <gazebo reference="arm_camera_holder">
    <material>Gazebo/Grey</material>
  </gazebo>


  <joint name="arm_camera_joint" type="fixed">
    <parent link="arm_camera_holder"/>
    <child link="camera_link"/>
    <!-- Effort in Nm, angle in radians -->
    <origin xyz ="0 ${RealsenseOriginSystem} -${CylinderRealsenseLength}" rpy="0 ${pi/2} 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name="camera_link">

  </link>

  <gazebo reference="camera_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  
</robot>