<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- import values from config.yaml file -->

  <xacro:arg name="config_path" default="$(find reseq_ros2)/config/reseq_mk1_can.yaml"/>
  <xacro:property name="config_path_prop" value="$(arg config_path)"/>

  <xacro:property name="config" value="${xacro.load_yaml(config_path_prop)}"/>
  <xacro:property name="a" value="${config['agevar_consts']['a']}" />
  <xacro:property name="b" value="${config['agevar_consts']['b']}" />
  <xacro:property name="r_eq" value="${config['agevar_consts']['r_eq']}" />

  <!-- See 'Parameters.pdf' pdf for parameters meaning (when it will exist ;) ) -->
  <!-- All values are in meters, radiants, kg -->
  
  <xacro:property name="toll" value="0.001"/>
  
  <!-- chassis related -->
  <xacro:property name="NumModules" value="${config['xacro']['NumModules']}"/>
  <xacro:property name="WheelBase" value="${config['xacro']['WheelBase']}"/>
  <xacro:property name="EquivalentWheelDiameter" value="${r_eq*2}"/>
  <xacro:property name="ModuleWidth" value="${config['xacro']['ModuleWidth']}"/>
  <xacro:property name="TrackWidth" value="${config['xacro']['TrackWidth']}"/>
  <xacro:property name="ChassisTopAndBottomClearance" value="${config['xacro']['ChassisTopAndBottomClearance']}"/>
  
  <xacro:property name="WheelMass" value="${config['xacro']['WheelMass']}"/>
  <xacro:property name="ChassisMass" value="${config['xacro']['ChassisMass']}"/>

  <!-- joint related -->
  <xacro:property name="JointDiameter" value="${config['xacro']['JointDiameter']}"/>
  <xacro:property name="JointA" value="${a-WheelBase/2}"/>
  <xacro:property name="JointB" value="${b-WheelBase/2}"/>
  <xacro:property name="JointABottomClearance" value="${config['xacro']['JointABottomClearance']}"/>
  <xacro:property name="JointWidth" value="${config['xacro']['JointWidth']}"/>

  <xacro:property name="pitch" value="${pi/2}"/>
  <xacro:property name="roll" value="${pi/2}"/>
  <xacro:property name="yaw" value="${pi/4}"/>

  <xacro:property name="JointAMass" value="${config['xacro']['JointAMass']}"/>
  <xacro:property name="JointBMass" value="${config['xacro']['JointBMass']}"/>

  <!-- arm related (only mk1) -->
  <xacro:property name="ForkThickness" value="${config['xacro']['ForkThickness']}"/>
  <xacro:property name="ForkHeight" value="${config['xacro']['ForkHeight']}"/>
  <xacro:property name="JetsonHolderLength" value="${config['xacro']['JetsonHolderLength']}"/>
  <xacro:property name="JetsonHolderWidth" value="${config['xacro']['JetsonHolderWidth']}"/>

  <!-- Rviz colors (for Gazebo ones change in single files) (from 0 to 1) -->
  <material name="ChassisColor">
    <color rgba="1 1 1 1" />
  </material>
  <material name="WheelColor">
    <color rgba="0 0 0 1" />
  </material>
  <material name="JointColor">
    <color rgba="0.5 0.5 0.5 1" />
  </material>
  <material name="ArmColor">
    <color rgba="0.5 0.5 0.5 1" />
  </material>
  <material name="LidarColor">
    <color rgba="0.5 0.5 0.5 1" />
  </material>

</robot>
