<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <link name="base_link" />

  <joint name="chassis1_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis1_link"/>
    <!-- leaving 1/3 of the EquivalentWheelDiameter from front (origin is in the center of eq wheel, at the bottom of the chassis) -->
    <origin xyz="0 0 ${(EquivalentWheelDiameter-2*ChassisTopAndBottomClearance)/2+ChassisTopAndBottomClearance}"/>
  </joint>

  <xacro:chassis id="1"/>
  <xacro:chassis_joint_factory id="2"/>
  <xacro:chassis id="2"/>


</robot>