---
canbus:
  channel: "can1"
modules:
  - address: 0x11
    hasJoint: false
    hasEndEffector: true
  - address: 0x12
    hasJoint: true
    hasEndEffector: false
  - address: 0x13
    hasJoint: true
    hasEndEffector: false
