- {
  msg_id: 0x21,
  modules: "all",
  length: 8,
  is_command: true,
  fields: [
    { name: "left_back_wheel",  type: "command", mode: "velocity", data_type: "float32", offset: 0, scale: 0.055, bias: 0.0 },
    { name: "right_back_wheel", type: "command", mode: "velocity", offset: 4, scale: 0.055 } # RPM to rad/s TIMES gain (0.52522)
  ]
}
- {
  msg_id: 0x22,
  length: 8,
  fields: [
    { name: "left_front_wheel",  mode: "velocity", type: "state", scale: 0.055 },
    { name: "right_front_wheel", mode: "velocity", offset: 4, scale: 0.055 },
    { name: "left_back_wheel",   mode: "velocity", scale: 0.055 },
    { name: "right_back_wheel",  mode: "velocity", offset: 4, scale: 0.055 },
  ]
}
- {
  msg_id: 0x32,
  modules: "skip_first",
  length: 4,
  fields: [
    { name: "yaw_joint", scale: 0.017453 }, # degrees to radians
  ]
}
# TODO: Add arm joints