name: "ROS2 CI/CD"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y iproute2
          apt-get install -y usbutils

      - uses: ros-tooling/setup-ros@v0.7
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble