controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    # wheel speed controller
    diff_cont_33:
      type: diff_drive_controller/DiffDriveController
    diff_cont_34:
      type: diff_drive_controller/DiffDriveController
    diff_cont_35:
      type: diff_drive_controller/DiffDriveController
    diff_cont_36:
      type: diff_drive_controller/DiffDriveController

    # joint position controller
    pos_cont_arm_mk1:
      type: forward_command_controller/ForwardCommandController
    pos_cont_joint_1:
      type: forward_command_controller/ForwardCommandController
    pos_cont_joint_2:
      type: forward_command_controller/ForwardCommandController
    pos_cont_joint_3:
      type: forward_command_controller/ForwardCommandController
    pos_cont_joint_4:
      type: forward_command_controller/ForwardCommandController

    # joint feedback
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# position controllers settings

pos_cont_arm_mk1:
  ros__parameters:
    joints:
      - arm_mK1_joint
    interface_name: position

pos_cont_joint_1:
  ros__parameters:
    joints:
      - joint_a_1_joint
      - joint_b_1_joint
    interface_name: position

pos_cont_joint_2:
  ros__parameters:
    joints:
      - joint_a_2_joint
      - joint_b_2_joint
      - chassis2_joint
    interface_name: position

pos_cont_joint_3:
  ros__parameters:
    joints:
      - joint_a_3_joint
      - joint_b_3_joint
      - chassis3_joint
    interface_name: position

pos_cont_joint_4:
  ros__parameters:
    joints:
      - chassis4_joint
    interface_name: position

# differential controllers settings

diff_cont_33:
  ros__parameters:
    publish_rate: 50.0

    odom_frame_id: odom
    base_frame_id: base_link

    left_wheel_names: ["left_front_wheel_1_joint", "left_back_wheel_1_joint"]
    right_wheel_names: ["right_front_wheel_1_joint", "right_back_wheel_1_joint"]
    wheel_separation: 0.13
    wheel_radius: 0.12

    use_stamped_vel: false
    enable_odom_tf: false
    enable_odom: false

diff_cont_34:
  ros__parameters:
    publish_rate: 50.0

    left_wheel_names: ["left_front_wheel_2_joint", "left_back_wheel_2_joint"]
    right_wheel_names: ["right_front_wheel_2_joint", "right_back_wheel_2_joint"]
    wheel_separation: 0.13
    wheel_radius: 0.12

    use_stamped_vel: false
    enable_odom_tf: false
    enable_odom: false

diff_cont_35:
  ros__parameters:
    publish_rate: 50.0

    left_wheel_names: ["left_front_wheel_3_joint", "left_back_wheel_3_joint"]
    right_wheel_names: ["right_front_wheel_3_joint", "right_back_wheel_3_joint"]
    wheel_separation: 0.13
    wheel_radius: 0.12

    use_stamped_vel: false
    enable_odom_tf: false
    enable_odom: false

diff_cont_36:
  ros__parameters:
    publish_rate: 50.0

    left_wheel_names: ["left_front_wheel_4_joint", "left_back_wheel_4_joint"]
    right_wheel_names: ["right_front_wheel_4_joint", "right_back_wheel_4_joint"]
    wheel_separation: 0.13
    wheel_radius: 0.12

    use_stamped_vel: false
    enable_odom_tf: false
    enable_odom: false
